my_app/add_bp/__init__.py
from flask import Blueprint

add_bp = Blueprint('add_bp', __name__, template_folder='templates')

from . import routes

my_app/add_bp/routes.py
from . import add_bp
from flask import render_template, redirect, url_for
from my_app import db
from my_app.forms import PostForm
from my_app.models import Post
from flask_login import current_user, login_required

@add_bp.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    form = PostForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:
            new_post = Post(title=form.title.data, content=form.content.data, author=current_user)
            db.session.add(new_post)
            db.session.commit()
            return redirect(url_for('main_bp.home'))

    return render_template('add_bp/add.html', title='Добавление статьи', form=form)

my_app/add_bp/templates/add_bp/add.html
{% extends 'base.html' %}
{% from '_formhelpers.html' import render_field %}

{% block content %}
<div class="form-wrapper">
    <img class="form-logo" src="{{ url_for('static', filename='img/logo.png') }}" alt="Логотип">
    <h2>Добавление статьи</h2>
    
    <form method="post" action="{{ url_for('add_bp.add') }}"> 
        {{ form.hidden_tag() }}
        
        <div class="form-group">
            {{ render_field(form.title, class="form-control", placeholder="Заголовок статьи") }}
        </div>
        <div class="form-group">
            {{ render_field(form.content, class="form-control", placeholder="Текст статьи", rows="8") }}
        </div>
        
        <button class="btn btn-primary btn-block" type="submit">Добавить статью</button>
    </form>
</div>
{% endblock %}